cv:
  n_splits: 5
data:
  columns:
  - utc_timestamp
  - NL_load_actual_entsoe_transparency
  freq_minutes: 15
  horizon: 96
  lookback: 1440
  source: data/raw/time_series.sqlite
  table: time_series_15min_singleindex
  target: NL_load_actual_entsoe_transparency
  timestamp_col: utc_timestamp
  timestamp_format: '%Y-%m-%dT%H:%M:%SZ'
  weather:
    columns:
    - utc_timestamp
    - NL_temperature
    - NL_radiation_direct_horizontal
    source: data/raw/weather_data.sqlite
    table: weather_data
    timestamp_col: utc_timestamp
    timestamp_format: '%Y-%m-%dT%H:%M:%SZ'
    use: true
features:
  lags:
  - 0
  - 1
  - 4
  - 12
  - 96
  - 672
  rolls:
  - 96
  - 288
  - 672
model:
  cnn_conv_channels: 32
  cnn_conv_dropout: 0.20096200307649678
  cnn_dilation_base: 2
  cnn_kernel_size: 3
  cnn_num_conv_layers: 3
  cnn_use_batchnorm: true
  feature_input_size: 215
  lstm_dropout: 0.27944775205529054
  lstm_hidden_size: 256
  lstm_num_layers: 2
  name: CnnLSTM
  output_size: 96
  windows_input_size: 3
seed: 42
split:
  train_val_split: 0.9
  trainval_test_split: 0.8
train:
  batch_size: 128
  epochs: 99
  learning_rate: 0.0005556436019751606
  n_trials: 100
  patience: 10
  weight_decay: 0.000566556467567383
