seed: 42
data:
  target: NL_load_actual_entsoe_transparency
  freq_minutes: 15
  lookback: 96
  horizon: 96
features:
  lags: [0, 1, 4, 12, 96]
  rolls: [96]
cv:
  n_splits: 2
split:
  trainval_test_split: 0.8
  train_val_split: 0.9

model:
  name: CnnLSTM
  # These parameters are fixed for all trials
  dilation_base: 2
  use_batchnorm: true
train:
  epochs: 100
  patience: 10
  hpo:
    n_trials: 1 
    learning_rate:
      low: 0.0001
      high: 0.001
      log: true
    weight_decay:
      low: 1.0e-5  
      high: 1.0e-3
      log: true
    batch_size:
      choices: [128, 256]
    conv_channels:
      choices: [32, 64]
    num_conv_layers:
      choices: [2, 3]
    kernel_size:
      choices: [3, 5]
    conv_dropout:
      low: 0.1
      high: 0.3 
    hidden_size: 
      choices: [256, 512]
    num_layers: 
      choices: [2, 3]
    dropout: 
      low: 0.2
      high: 0.4