seed: 42
data:
  target: NL_load_actual_entsoe_transparency
  freq_minutes: 15
  lookback: 1440
  horizon: 96
features:
  lags: [0, 1, 4, 12, 96, 672]
  rolls: [96, 288, 672]
cv:
  n_splits: 5
split:
  trainval_test_split: 0.8
  train_val_split: 0.9

model:
  name: CnnLSTM
  # These parameters are fixed for all trials
  cnn_dilation_base: 2
  cnn_use_batchnorm: true
  cnn_conv_channels: 32
  cnn_num_conv_layers: 3
  cnn_kernel_size: 3
  cnn_conv_dropout: 0.20096200307649678
  lstm_hidden_size: 256
  lstm_num_layers:  2
  lstm_dropout:  0.27944775205529054
train:
  epochs: 99
  patience: 10
  n_trials: 100
  learning_rate: 0.0005556436019751606
  weight_decay: 0.000566556467567383
  batch_size: 128 

