seed: 42
data:
  target: NL_load_actual_entsoe_transparency
  freq_minutes: 15
  lookback: 1440
  horizon: 96
features:
  lags:
  - 0
  - 1
  - 4
  - 12
  - 96
  - 672
  rolls:
  - 96
  - 288 
  - 672 
model:
  name: CnnLSTM
  # CNN properties
  conv_channels:
  - 64
  num_conv_layers:
  - 3
  kernel_size:
  - 5
  dilation_base:
  - 2
  conv_dropout:
  - 0.24507
  use_batchnorm:
  - true
  # LSTM properties 
  hidden_size: 
  - 128
  num_layers: 
  - 2
  dropout: 
  - 0.21962
train:
  batch_size: 
  - 64
  learning_rate: 
  - 0.00073
  weight_decay: 
  - 0.00045
  epochs: 
  - 100
  patience: 
  - 10
cv:
  n_splits: 5
split:
  trainval_test_split: 0.8
  train_val_split: 0.9
