seed: 42
data:
  target: NL_load_actual_entsoe_transparency
  freq_minutes: 15
  lookback: 720
  horizon: 96
features:
  lags: [0, 1, 4, 12, 96, 672]
  rolls: [96, 288, 672]
cv:
  n_splits: 4
split:
  trainval_test_split: 0.8
  train_val_split: 0.9

model:
  name: CnnLSTM
  cnn_dilation_base: 2
  cnn_use_batchnorm: true
  cnn_conv_channels:
    choices: [32, 64]
  cnn_num_conv_layers:
    choices: [2, 3]
  cnn_kernel_size:
    choices: [3, 5]
  cnn_conv_dropout:
    low: 0.1
    high: 0.3 
  lstm_hidden_size: 
    choices: [128, 256, 512]
  lstm_num_layers: 
    choices: [2, 3]
  lstm_dropout: 
    low: 0.2
    high: 0.4
train:
  epochs: 100
  patience: 10
  n_trials: 100 
  learning_rate:
    low: 0.0001
    high: 0.001
    log: true
  weight_decay:
    low: 1.0e-5  
    high: 1.0e-3
    log: true
  batch_size:
    choices: [64, 128, 256]
  