seed: 42
data:
  target: NL_load_actual_entsoe_transparency
  freq_minutes: 15
  lookback: 96
  horizon: 96
features:
  lags: [0, 1, 4, 12, 96, 672]
  rolls: [96, 288, 672]
cv:
  n_splits: 5
split:
  trainval_test_split: 0.8
  train_val_split: 0.9

model:
  name: CnnLSTM
  # These parameters are fixed for all trials
  cnn_dilation_base: 2
  cnn_use_batchnorm: true
  cnn_conv_channels: 64
  cnn_num_conv_layers: 2 
  cnn_kernel_size: 3
  cnn_conv_dropout: 0.1
  lstm_hidden_size: 128
  lstm_num_layers:  2
  lstm_dropout:  0.2
train:
  epochs: 1
  patience: 10
  n_trials: 2 
  learning_rate: 0.0001
  weight_decay: 1.0e-5
  batch_size: 64
  